# Generated by Django 5.1.7 on 2025-04-06 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_address_options_alter_client_name_clientphone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
        migrations.AlterModelOptions(
            name='clientphone',
            options={'verbose_name': 'Client Phone', 'verbose_name_plural': 'Client Phones'},
        ),
    ]
